apiVersion: v1
kind: Secret

metadata:
  name: vault-token
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  token: {{ .Values.vault.token }}

---

apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: {{ .Values.vault.secretStoreName }}
  namespace: {{ .Release.Namespace }}

spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}

      auth:
        tokenSecretRef:
          name: vault-token
          key: token

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore

  target:
    name: {{ .Values.externalSecret.targetSecret }}

  data:
    - secretKey: username

      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: username

    - secretKey: password

      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: password

    - secretKey: MONGO_URI

      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MONGO_URI
