apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: student-api-project
  namespace: argocd

spec:
  description: Student API GitOps Project

  sourceRepos:
    - '*'

  destinations:
    - namespace: student-api
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'